AllCops:
  Severity: fatal
  NewCops: enable
  SuggestExtensions: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# To disable warnings in "do <<-RUBYCODE..."
Layout/MultilineBlockLayout:
  Enabled: false

# # Don't know if OK to disable.
# Style/FrozenStringLiteralComment:
#   Enabled: false

Style/AndOr:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/FirstHashElementIndentation:
  Enabled: false
