services:
  ruby-dev:
    image: ruby:2.1.1
    command: tail -F keepthisrunning
    volumes:
      - ./:/app
    container_name: ruby-dev
    entrypoint:

# `docker exec -it ruby-dev bash -c cd /app`